### ISSUE TITLE
Swift project with Cocoapods

### ISSUE THREAD

**Issue by xmellado** [jiulongw/swift-unity#16]
Hello,

I have been trying to integrate a Unity project inside my Swift app. I am using some external libraries such as Facebook, RxSwift or SwiftyBeaver managed with Cocoapods.

Your example alone works fine, but when I try to follow your instructions to reproduce the integration inside my app, I face a problem with file `Unity.xcconfig`. I cannot integrate its contents inside the xcconfig file generated by Cocoapods, when I copy and paste Unity config file contents inside, the prefix.pch file throws an error. After some modifications to the variables, I found a dead end. Either the code of my app compiles, or the imported libraries compile, but I was not able to make both compile at the same time.

Do you have tested this approach with a Swift project that uses Cocoapods? Do you have any advice?

Thanks in advance,
Xavi

**Comment by jiulongw** [comment]
Yes I have tested Unity with GVR which contains several Cocoapods packages.  I documented steps in the comments of [Unity.xcconfig](https://github.com/jiulongw/swift-unity/blob/master/demo/xcode/DemoApp/Unity/Unity.xcconfig).

The `xcconfig` does not support same variable substitution in the same file.  You need to make sure you don't override any variable by mistake.  For example,
```
OTHER_CFLAGS=$(inherited) -DFLAG1
...
OTHER_CFLAGS=$(OTHER_CFLAGS) $-DFLAG2
```
I thought `OTHER_CFLAGS` would contain both `-DFLAG1` and `-DFLAG2` but no, the second one completely overrides the first one.  So if you simply copy contents from `Unity.xcconfig` to your Cocoapods `xcconfig` file, chances are you're overriding many settings.

I would suggest to follow comments in `Unity.xcconfig` and use `Unity.xcconfig` as the configuration file instead of Cocoapod generated one, so that you don't need to do the same thing again every time Unity generates new build.

**Comment by phucnm** [comment]
I'm using CocoaPods in an integrated Unity-iOS application. Currently I use Unity.xcconfig file for configuration and include Pods config at the top of it. They're all fine FYI.

```
#include "Pods/Target Support Files/Pods-xxx/Pods-xxx.debug.xcconfig"
#include "Pods/Target Support Files/Pods-xxx/Pods-xxx.release.xcconfig"
```

**Comment by xmellado** [comment]
Hello,
@jiulongw Thanks for the quick response and the extra information. I appreciate it. I read your comments in `Unity.xcconfig`, but I thought comments were only for Unity projects using Cocoapods. My case is the complementary, my Swift project uses Cocoapods.
@phucnm Thanks a lot! Your includes did the trick. My project is now compiling and running.
Best regards,
Xavi
