### ISSUE TITLE
GVRSDK : Unrecognised selector sent to instance

### ISSUE THREAD

**Issue by jplongo** [jiulongw/swift-unity#3]
My project build and run well, but when I try to use VR on my Unity project with GVRSDK, I have a crash with 'Unrecognised selector error'

Does anybody already issue this kind of crash ?
![2017-10-07 at 11 24 am](https://user-images.githubusercontent.com/22789876/31306527-5c76b6b2-ab52-11e7-960d-e70720cf2df5.png)

I've added a symbolic breakpoint and know that crash come on this line :

![2017-10-07 at 12 19 pm](https://user-images.githubusercontent.com/22789876/31307150-1fa671d0-ab5e-11e7-99a4-cbc468814af7.png)

My project is in Swift 4, run on Xcode 9 and Unity 2017.1.1f1

**Comment by jiulongw** [comment]
`[UICTFont mdc_weight]: unrecognized selector sent to instance` means calling a method / property that does not exist.

It seems to be some code in libGVRSDK.a which I cannot find source code...

```
$ grep -R . -e mdc_weight
Binary file ./Pods/GVRSDK/Libraries/libGVRSDK.a matches
```

I'm no expert of GVR SDK but I would check

- Whether the fonts used by GVR SDK properly copied to the iOS app
- Try latest GVR SDK see if this is because you're using newer version of Xcode and Unity
- See if Unity exported Xcode project can be run without this crash (actually I don't think this is a Swift project looking at the stack trace...)
- Send this bug report to GVR SDK repo to see if they can help

**Comment by jplongo** [comment]
I spend all my day to try to know more about this crash.
I’ve checked all fonts and everything is correctly linked in the .bundle file. I’ve copied the SDK directly in my project to prevent this kind of issue. But no change. 

Unity build on Xcode 9 and run on iOS 11 with both 1.60 and 1.80 SDK release. I’ve downloaded last github commit to be sure. And no way. 

My project use swift 4 but the unity output here is in c++. 
And as like you I can’t get the code execution inside library so can’t break at the exactly line. I just can view when upper method is called in obj-c

I’m agree with you. My last plan is to post an issue on GVR git.

Many thanks for your great answer. I will post a comment if I have an answer on GRV git

**Comment by jiulongw** [comment]
Hey @jplongo , I tried this morning and was able to embed GVR into Swift project.  I did encounter the exact problem you met about `mdc_weight`.  It can be fixed by adding `-objC` into `OTHER_LDFLAGS`.

I don't know how you managed to build your project but I copied (merged) all settings from `Pods-Unity-iPhone.release.xcconfig` and adding all `.bundles` files to build target.

This reminds me about other issues I had when adding WebRTC into Unity iOS app where I need to add `-objC` flag to solve a weird crash...  I will dig into it to see if it make sense to always add it to LDFLAGS.

Hope that resolves your issue.

**Comment by jiulongw** [comment]
> Q:  How do I fix "selector not recognized" runtime exceptions when trying to use category methods from a static library?

https://developer.apple.com/library/content/qa/qa1490/_index.html

It seems like if your project uses a static linked library you need `-objC` flag.

**Comment by jplongo** [comment]
Hi, Thanks for help.
Unfortunately -OBjc does not solve my problem. But your tips about merging config file is good.
I've already tried to do that but without success. I've many linker error and when project build, the same `mdc_weight` crash pop.

I'm really curious to compare your merged config file and how you integrate Pod files in your project. It can certainly fix my issue.

Thanks 👍

**Comment by jiulongw** [comment]
I'm pretty sure `-objC` is the solution because removing `-objC` was the only change I made that causes a running app throws `[UICTFont mdc_weight]: unrecognized selector sent to instance`.  I guess you didn't add `-objC` to the right place.  I don't know how you manage these .xcconfig files but adding `-objC` to .xcconfig file could be overridden or ignored depends on your build settings.

You can try to add `-objC` to project build settings.  Toggle on all settings and show override levels you can see how your settings are applied.

![screen shot 2017-10-10 at 10 08 53 am](https://user-images.githubusercontent.com/1650734/31400072-304b18d2-ada3-11e7-9e35-cbf6cd3a704f.png)

Regarding merging Pod files to Swift project... I did the quick & dirty way by manually add Pod outputs (`.a` and `.bundle`s) to Swift project and add `.bundle`s to the build target.  Also you need to set`HEADER_SEARCH_PATHS` and `LIBRARY_SEARCH_PATHS` properly.  So there is no Pod files in my test Swift project.

If you want I can cleanup and pack a project for you to take a look when I get time (probably later this week) but as I said before, there is no Pod integration...

**Comment by jplongo** [comment]
I really would like that -ObjC solve my problem. Perhaps it's one of the n elements causing this crash. Unfortunately I've tried many things with no success. 
I've the same libs, the same .bundles files linked in target. So I'm sure I miss something but I need to find what...

It would be a pleasure if you can share me a project with GVRSDK embedded. I will compare your work and hope find the way to get my app working with VR.

Thanks for taking time to help me 👍 

![2017-10-11 at 11 05 am](https://user-images.githubusercontent.com/22789876/31431811-004d654a-ae75-11e7-9981-2078a5e4ea53.png)
![2017-10-11 at 11 05 amdd](https://user-images.githubusercontent.com/22789876/31431812-00743a76-ae75-11e7-8565-50662a6c4bf7.png)

**Comment by gautamb0** [comment]
@jiulongw I'm also keenly watching this, as I also need GVR. I'm still stuck on linker errors and would also greatly appreciate learning your merging process. I added the entire Pods folder, but it seems like your method is far more elegant. Thank you so much for putting this repository together; it has been a great help.

**Comment by jplongo** [comment]
It seems that the problem come from AWS. I'm using AWSSDK on my project and one of the framework don't like -ObjC flag.
I'm trying to replace -ObjC flag with -force_load as mentioned, but it don't change anything. I think I did something wrong but I'm trying to find what yet...

https://github.com/aws/aws-mobilehub-helper-ios/issues/8

**Comment by jplongo** [comment]
Ok finally I reload all my ldflags config and add -force_load to the GVRSDK.a library and now I'm able to load Unity view on my project.
`But` I have a blank screen after selecting cardboard profile. 
I will take a look on google to find informations about this new problem on my project.
If you have some clues feel free...

Many many thanks for helping me. It's really appreciate

**Comment by jiulongw** [comment]
@jplongo Glad you have solved the problem!  First of all I made a mistake that the `-ObjC` flag is case sensitive and I incorrectly typed `-objC` everywhere...  I see you also put `-objC` from your screen shot.  It should be `-ObjC` otherwise it is ignored...  Sorry about that.

@gautamb0 I've updated [Unity.xcconfig][1] file with steps you need to handle GVR SDK.  You need to put [PostBuild.cs][2] into your Unity project (make sure it is under `Editor` folder), build the generated Xcode project and then follow steps in [Unity.xcconfig][1].  I have verified it builds and runs well.  Let me know if you have any questions.

[1]: https://github.com/jiulongw/swift-unity/blob/master/demo/xcode/DemoApp/Unity/Unity.xcconfig
[2]: https://github.com/jiulongw/swift-unity/blob/master/demo/unity/Assets/Scripts/Editor/PostBuild.cs

**Comment by gautamb0** [comment]
Awesome! I got the clue from your earlier comment of getting the pod outputs, and actually ended up following the same steps last night after failing to get it working with the entire pod copied in (probably for the better...) If anyone else is watching, GVR has a known bug in iOS with spatial audio referenced [here](https://github.com/googlevr/gvr-unity-sdk/issues/665) which can cause it to crash immediately upon entering Cardboard mode. My solution was to just not use spatial audio, but there is a patch provided. My final problem is that it's not responding to touch but I assume that's a problem with the view hierarchy.

**Comment by gautamb0** [comment]
Hi guys, this is probably not the right place for this, but you're the best two to ask since you've already implemented this. It seems like the GVR overlay somehow prevents the app from responding to touch altogether. @jplongo I'm guessing you've fixed this since you mentioned being able to select a cardboard profile. How are you loading the view? Any special tricks? Thanks!

**Comment by jiulongw** [comment]
@gautamb0 how do you add Unity view to Swift view?  You need to add it behind Swift UIView.  See [this example][1].

[1]: https://github.com/jiulongw/swift-unity/blob/a308657968441ce71c2a76151489a295d5bfde9e/demo/xcode/DemoApp/ViewController.swift#L22

**Comment by gautamb0** [comment]
I've been using your code exactly as-is. Even if I use your sample application, but select virtual reality supported in Unity, the screen does not respond to touch at all, even for the "Rotate" slider. Guess I must be doing something wrong somewhere...

**Comment by jplongo** [comment]
Here is how I load Unity as subView in a ViewController. Nothing special here, I've just followed original method from https://github.com/blitzagency/ios-unity5.

![2017-10-16 at 8 54 am](https://user-images.githubusercontent.com/22789876/31598859-3945cd86-b250-11e7-8f5e-b661b4e14d2e.png)

Control seems to work fine, I can scan my VR Headset. But as described in my previous com, when view is loaded, I just have a white screen and can't do anything. App is running but no display.
I will try to find why and how to solve it this week but I think Metal is buggy on Unity 2017.1.1f1
@jiulongw Did you try to display VR view on your DemoApp ?

**Comment by jplongo** [comment]
Here is how I load Unity as subView in a ViewController. Nothing special here, I've just followed original method from https://github.com/blitzagency/ios-unity5.

![2017-10-16 at 8 54 am](https://user-images.githubusercontent.com/22789876/31598859-3945cd86-b250-11e7-8f5e-b661b4e14d2e.png)

Control seems to work fine, I can scan my VR Headset.  ~~But as described in my previous com, when view is loaded, I just have a white screen and can't do anything. App is running but no display.
I will try to find why and how to solve it this week but I think Metal is buggy on Unity 2017.1.1f1~~

EDIT : GVRSDK work fine now, but. One big problem is missing now, the view don't fit my iPhone 6s screen. Need to find why now...

<img width="667" alt="image" src="https://user-images.githubusercontent.com/22789876/31604482-c05bf562-b263-11e7-86b9-012f83275a7f.png">

@jiulongw Did you try to display VR view on your DemoApp ?

**Comment by jplongo** [comment]
@jiulongw Any idea about [this](https://github.com/googlevr/gvr-unity-sdk/issues/780) issue ?

**Comment by jplongo** [comment]
@jiulongw I know that this is not an issue on your demoProject but if you can grab more informations about my [issue](https://github.com/googlevr/gvr-unity-sdk/issues/780) ?
There is a sample project with encountered issue

Thanks

**Comment by jiulongw** [comment]
@jplongo I'm not actively working on swift and unity recently.  Will take a look if I get chance some day.

**Comment by jiulongw** [comment]
@jplongo I tried you app today and was able to repro the issue.  You're right this only happens after loading VR view so I think this should be GVR issue.  Just FYI embedding Unity into iOS app is not officially supported.  It will probably be a low priority issue even if GVR folks accept the bug...

**Comment by jplongo** [comment]
Yep unfortunately this is what I think. Try to find another way by reloading my iOS App, but no way at this time.

Thanks
