### ISSUE TITLE
[Help] Unable to link Xcode 9.1 and Unity 2017.3.0f3 (2017.2.0f3 too)

### ISSUE THREAD

**Issue by shmiftari** [jiulongw/swift-unity#33]
For many days I'm trying different methods but still unable to make a working simple app with unity and xcode (latest versions both)

![screen shot 2017-12-28 at 11 34 50 am](https://user-images.githubusercontent.com/25005908/34409171-57a14f88-ebc8-11e7-849e-b13a65390892.png)
https://i.imgur.com/vf59LHh.png

From the image below we can see that the files are found, what I tried is to delete the folder path, then it works but this happens to all .cpp files, I tried but then the methods are not recognized, tried many different things, by commenting some functions then by including other files like "UnityInterface.h" etc... but I know that this isn't going to work.

One thing to add is that the Classes and Libraries folders are not being copied into the Xcode main project, I'm adding them manually because I get all of them red.

Could someone please help me, I have a stable project in swift 2.3 and unity 5.4.2 but want to upgrade to swift 3 or 4 (optionally).

Thank you.

**Comment by jiulongw** [comment]
Having this kind of screenshot does not help a lot.  It only tells your header search path isn't right so Xcode cannot find some required header files.

Things are easy to miss if you're doing everything manually that's why I recommend the automated post build scripts.  You can always compare the build settings of your swift project with the Unity generated Xcode project to see what is missing.

Something worth checking:
1. Your header search path is probably wrong
2. Xcode 9 seems to have a bug that if you drag-n-drop a folder into Xcode project tree and create group, regardless you choose to add files to build target or not, the .mm files are not added to build target. A work around is to right click Xcode project tree and select add files from there.
3. Try to use the [post build script](https://github.com/jiulongw/swift-unity/blob/master/XcodePostBuild.cs).

**Comment by jiulongw** [comment]
Feel free to re-open this issue if you still have problems.
