### ISSUE TITLE
UnityGfxDeviceWorker (18): EXC_BAD_ACCESS (code=1, address=0x1)

### ISSUE THREAD

**Issue by joeshonm** [jiulongw/swift-unity#4]
I know that this project is directly focused on integrating Unity and does not cover integrating Unity with Vuforia. Everything runs with no issues except after I run startUnity. 

We are using Vuforia and the camera is used in the view. However I'm getting the error below that from my research it has to deal with Unity creating a texture for the camera. The Unity app runs by itself perfectly fine with the camera being used, but after integrating with my swift project I'm getting this issue.

I'm attaching an image of the error as it was difficult to add here with proper styling. The overall error is:

0x1033e81b0 <+44>:  mov    x19, x0 **"This where the UnityGfxDeviceWorker (18): EXC_BAD_ACCESS (code=1, address=0x1) happens"**

**The console output ends with:**
Setting up 1 worker threads for Enlighten.
  Thread -> id: 16dbef000 -> priority: 1 
UnloadTime: 2.160708 ms
Compiled for iOS
Vuforia.PlatformRuntimeInitialization:InitPlatform()
System.Collections.Generic.HashSet`1:GetEnumerator()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by jiulongw** [comment]
This might be related to [this change][1] I made to Unity generated code, which was intended to solve a crash in `UnityGfxDeviceWorker`.  I don't know the root cause, but made this change purely from suggestion of the crash message.  There could be unknown side effect caused by this change.

You can try couple of things:
1. Undo this change and see if it fixes your problem.
2. Try to set different GL API using `Vuforia::setInitParameters`.  I think the fix was targeted to METAL API, not sure if by default Vuforia uses *OpenGL ES*.

Quote from README.md about this change:
> * Classes/Unity/MetalHelper.mm
> 
>   Add `MTLTextureUsageRenderTarget` to the stencil texture descriptor to fix runtime assertion failure. Not sure if this is a bug in Xcode or Unity but following line fixed the issue.
> 
>   ```
>   stencilTexDesc.usage |= MTLTextureUsageRenderTarget;
>   ```

[1]: https://github.com/jiulongw/swift-unity/blob/6bacdba042fbd99b4bb84161ae747e1fa4d22e05/demo/xcode/DemoApp/Unity/Classes/Unity/MetalHelper.mm#L192

**Comment by jiulongw** [comment]
Also, try to add `-objC` to `OTHER_LDFLAGS` if Vuforia is a static linked library.

**Comment by joeshonm** [comment]
Thanks again @jiulongw I was able to get past the issue. Also found out my team member didn't add the scene in Unity build settings.

**Comment by ohwhen** [comment]
Apologies for kicking this thread alive but @joeshonm would you care to share how you got past this issue?

**Comment by bilalpakeermohamed** [comment]
@joeshonm  Could you please share the solution? @ohwhen Were you able to find a fix?
